### ISSUE TITLE
some icons are not showing ?

### ISSUE THREAD

**Issue by RimazFlyil** [nothingButSyntaxError/dotfiles#3]
some icons are not showing ? volume, wifi , temperature icons are not showing

**Comment by p4rthh** [comment]
you should have all the fonts that are required installed. The fonts required are:
```ini
font-0 = JetBrains Mono Nerd Font:style=Bold:pixelsize=16;3
font-1 = JetBrainsMono Nerd Font:size=25;6
font-2 = Material Design Icons:style=Bold:size=18;4
font-3 = JetBrains Mono Nerd Font:style=Bold:size=15;3
font-4 = JetBrainsMono Nerd Font:size=19;4
font-5 = JetBrainsMono Nerd Font:style=Bold:size=13;3
font-6 = JetBrainsMono Nerd Font:size=21;4
font-7 = Material Design Icons:style=Bold:size=15;2
font-8 = JetBrainsMono Nerd Font:style=Bold:size=12;3
font-9 = unifont:fontformat=truetype:size=12;3
```

**Comment by RimazFlyil** [comment]
if u dont mind can you please upload your fonts please

**Comment by p4rthh** [comment]
https://github.com/ryanoasis/nerd-fonts you can get the fonts from this github page and also from their website (i prefer to download from the website since its easy to navigate) https://nerdfonts.com. If you still want me to upload cuz you couldnt figure out something do let me know

**Comment by p4rthh** [comment]
Umm, I am closing this issue since there has been no reply from you. If you have any more problems you can open it again. Thanks!
